/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistempenjualan.desain;

import java.sql.SQLException;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import sistempenjualan.Main;
import sistempenjualan.model.TransaksiPenjualan;

/**
 *
 * @author altintop
 */
public class PanelKasir2 extends javax.swing.JInternalFrame {

    private TransaksiPenjualan modelTransaksi; //model kita
    int totbayar, harga, jumlah;
    String totbayar1;

    /**
     * Creates new form PanelKasir
     */
    public PanelKasir2() throws SQLException {
        initComponents();
        setWaktu();
        modelTransaksi = new TransaksiPenjualan();
        this.tabelKasir.setModel(modelTransaksi.getTabel());
        hilang();
    }

    public void setWaktu() {
        Date ys = new Date();
        SimpleDateFormat s = new SimpleDateFormat("yyyy-MM-dd");
        tanggalField.setText(s.format(ys));
    }
    
    public void hilang() {
        satuanField.setVisible(false);
    }

    public JTable getTabelKasir() {
        return tabelKasir;
    }

    public JTextField getKasir() {
        return kasirField;
    }

    public JTextField getBarang() {
        return barangField;
    }

    public JTextField getJumlah() {
        return jumlahField;
    }

    public JTextField getTanggal() {
        return tanggalField;
    }

    public JTextField getTotalBayar() {
        return totalHargaField;
    }

    public JTextField getSatuan() {
        return satuanField;
    }

    public JComboBox getKodeBarang() {
        return kodeComboBox;
    }

    public void hargaSatuan() {
        int pilihan = kodeComboBox.getSelectedIndex();
        switch (pilihan) {
            case 0:
                satuanField.setText("2000");
                break;
            case 1:
                satuanField.setText("5000");
                break;
            case 2:
                satuanField.setText("10000");
                break;
            case 3:
                satuanField.setText("20000");
                break;
        }
    }

    public void total() {
        harga = Integer.parseInt(jumlahField.getText());
        jumlah = Integer.parseInt(satuanField.getText());
        totbayar = harga * jumlah;
        DecimalFormat f = new DecimalFormat("#.#");
        totbayar1 = String.valueOf(f.format(totbayar));
        totalHargaField.setText(totbayar1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        barangField = new javax.swing.JTextField();
        jumlahField = new javax.swing.JTextField();
        kodeBarangLabel = new javax.swing.JLabel();
        tanggalField = new javax.swing.JTextField();
        namaBarangLabel = new javax.swing.JLabel();
        totalHargaField = new javax.swing.JTextField();
        jumlahLabel = new javax.swing.JLabel();
        kasirField = new javax.swing.JTextField();
        totalHargaLabel = new javax.swing.JLabel();
        kasirLabel = new javax.swing.JLabel();
        tanggalLabel = new javax.swing.JLabel();
        tambahButton = new javax.swing.JButton();
        bayarButton = new javax.swing.JButton();
        jScrollPane = new javax.swing.JScrollPane();
        tabelKasir = new javax.swing.JTable();
        kodeComboBox = new javax.swing.JComboBox();
        satuanField = new javax.swing.JTextField();

        setClosable(true);
        setTitle("Kasir");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/sistempenjualan/images/kasir_16.png"))); // NOI18N
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jumlahField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jumlahFieldActionPerformed(evt);
            }
        });
        jumlahField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jumlahFieldKeyReleased(evt);
            }
        });

        kodeBarangLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        kodeBarangLabel.setText("Kode Barang");

        namaBarangLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        namaBarangLabel.setText("Nama Barang");

        totalHargaField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalHargaFieldActionPerformed(evt);
            }
        });

        jumlahLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jumlahLabel.setText("Jumlah");

        totalHargaLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        totalHargaLabel.setText("Total Harga");

        kasirLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        kasirLabel.setText("Nama Kasir");

        tanggalLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tanggalLabel.setText("Tanggal");

        tambahButton.setText("Tambah");
        tambahButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahButtonActionPerformed(evt);
            }
        });

        bayarButton.setText("Bayar");
        bayarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bayarButtonActionPerformed(evt);
            }
        });

        tabelKasir.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane.setViewportView(tabelKasir);

        kodeComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1001", "1002", "1003", "1004", "1005" }));
        kodeComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kodeComboBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jumlahLabel)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tanggalLabel)
                            .addComponent(totalHargaLabel))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tanggalField, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(totalHargaField, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addComponent(satuanField, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(namaBarangLabel)
                                    .addComponent(kasirLabel))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(barangField)
                                    .addComponent(jumlahField, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                                    .addComponent(kasirField)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(kodeBarangLabel)
                                .addGap(18, 18, 18)
                                .addComponent(kodeComboBox, 0, 101, Short.MAX_VALUE)))
                        .addGap(60, 60, 60)
                        .addComponent(tambahButton)
                        .addGap(18, 18, 18)
                        .addComponent(bayarButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kasirLabel)
                    .addComponent(kasirField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kodeBarangLabel)
                    .addComponent(kodeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(namaBarangLabel)
                            .addComponent(barangField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jumlahLabel)
                            .addComponent(jumlahField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(tanggalField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(satuanField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(tanggalLabel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(totalHargaLabel)
                            .addComponent(totalHargaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tambahButton)
                            .addComponent(bayarButton))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tambahButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahButtonActionPerformed
        String Kasir = getKasir().getText();
        String Kode = (String) getKodeBarang().getSelectedItem();
        String Barang = getBarang().getText();
        String Jumlah = getJumlah().getText();
        String Tanggal = getTanggal().getText();
        String Totalbayar = getTotalBayar().getText();
        modelTransaksi.Tambah(Kasir, Kode, Barang, Jumlah, Tanggal, Totalbayar);
        try {
            modelTransaksi = new TransaksiPenjualan();
        } catch (SQLException ex) {
            Logger.getLogger(PanelKasir2.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.tabelKasir.setModel(modelTransaksi.getTabel());
        JOptionPane.showMessageDialog(null, "Data berhasil masuk", "MultiRasa", 1);
        getKasir().setText("");
        getBarang().setText("");
        getJumlah().setText("");
        getTanggal().setText("");
        getTotalBayar().setText("");
    }//GEN-LAST:event_tambahButtonActionPerformed

    private void bayarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bayarButtonActionPerformed
        JOptionPane.showMessageDialog(null, "Popup Pembayaran", "MultiRasa", 1);
    }//GEN-LAST:event_bayarButtonActionPerformed

    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing
        Main.getFrameUtama().panelKasir = null;
        System.out.println("sudah di null pas ditutup: " + Main.getFrameUtama().panelKasir);
    }//GEN-LAST:event_formInternalFrameClosing

    private void kodeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kodeComboBoxActionPerformed
        hargaSatuan();
    }//GEN-LAST:event_kodeComboBoxActionPerformed

    private void jumlahFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jumlahFieldActionPerformed

    }//GEN-LAST:event_jumlahFieldActionPerformed

    private void totalHargaFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalHargaFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalHargaFieldActionPerformed

    private void jumlahFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jumlahFieldKeyReleased
        total();
    }//GEN-LAST:event_jumlahFieldKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField barangField;
    private javax.swing.JButton bayarButton;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JTextField jumlahField;
    private javax.swing.JLabel jumlahLabel;
    private javax.swing.JTextField kasirField;
    private javax.swing.JLabel kasirLabel;
    private javax.swing.JLabel kodeBarangLabel;
    private javax.swing.JComboBox kodeComboBox;
    private javax.swing.JLabel namaBarangLabel;
    private javax.swing.JTextField satuanField;
    private javax.swing.JTable tabelKasir;
    private javax.swing.JButton tambahButton;
    private javax.swing.JTextField tanggalField;
    private javax.swing.JLabel tanggalLabel;
    private javax.swing.JTextField totalHargaField;
    private javax.swing.JLabel totalHargaLabel;
    // End of variables declaration//GEN-END:variables
}
